language: python
python:
  - "3.9"
env:
  - DJANGO_SECRET_KEY=django_insecure
install:
  - pip install -r requirements.txt
before script:
  - python manage.py migrate
script:
  - flake8 .
  - python manage.py test